-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 19:48:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema usairlineflights2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usairlineflights2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usairlineflights2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `usairlineflights2` ;

-- -----------------------------------------------------
-- Table `usairlineflights2`.`carriers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usairlineflights2`.`carriers` (
  `CarrierCode` VARCHAR(32) NOT NULL,
  `Description` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`CarrierCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `usairlineflights2`.`usairports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usairlineflights2`.`usairports` (
  `IATA` VARCHAR(32) NOT NULL,
  `Airport` VARCHAR(80) NULL DEFAULT NULL,
  `City` VARCHAR(32) NULL DEFAULT NULL,
  `State` VARCHAR(32) NULL DEFAULT NULL,
  `Country` VARCHAR(32) NULL DEFAULT NULL,
  `Latitude` FLOAT NULL DEFAULT NULL,
  `Longitude` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`IATA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `usairlineflights2`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usairlineflights2`.`flights` (
  `flightID` INT(11) NOT NULL AUTO_INCREMENT,
  `colYear` SMALLINT(6) NULL DEFAULT NULL,
  `colMonth` SMALLINT(6) NULL DEFAULT NULL,
  `DayOfMonths` SMALLINT(6) NULL DEFAULT NULL,
  `DayOfWeek` SMALLINT(6) NULL DEFAULT NULL,
  `DepTime` SMALLINT(6) NULL DEFAULT NULL,
  `CRSDepTime` SMALLINT(6) NULL DEFAULT NULL,
  `ArrTime` SMALLINT(6) NULL DEFAULT NULL,
  `CRSArrTime` SMALLINT(6) NULL DEFAULT NULL,
  `UniqueCarrier` VARCHAR(32) NULL DEFAULT NULL,
  `FlightNum` VARCHAR(32) NULL DEFAULT NULL,
  `TailNum` VARCHAR(32) NULL DEFAULT NULL,
  `ActualElapsedTime` SMALLINT(6) NULL DEFAULT NULL,
  `CRSElapsedTime` SMALLINT(6) NULL DEFAULT NULL,
  `AirTime` SMALLINT(6) NULL DEFAULT NULL,
  `ArrDelay` SMALLINT(6) NULL DEFAULT NULL,
  `DepDelay` SMALLINT(6) NULL DEFAULT NULL,
  `Origin` VARCHAR(32) NULL DEFAULT NULL,
  `Dest` VARCHAR(32) NULL DEFAULT NULL,
  `Distance` SMALLINT(6) NULL DEFAULT NULL,
  `TaxiIn` SMALLINT(6) NULL DEFAULT NULL,
  `TaxiOut` SMALLINT(6) NULL DEFAULT NULL,
  `Cancelled` TINYINT(1) NULL DEFAULT NULL,
  `CancellationCode` VARCHAR(32) NULL DEFAULT NULL,
  `Diverted` TINYINT(1) NULL DEFAULT NULL,
  `CarrierDelay` SMALLINT(6) NULL DEFAULT NULL,
  `WeatherDelay` SMALLINT(6) NULL DEFAULT NULL,
  `NASDelay` SMALLINT(6) NULL DEFAULT NULL,
  `SecurityDelay` SMALLINT(6) NULL DEFAULT NULL,
  `LateAircraftDelay` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`flightID`),
  INDEX `Dest` (`Dest` ASC) VISIBLE,
  INDEX `Origin` (`Origin` ASC) VISIBLE,
  INDEX `UniqueCarrier` (`UniqueCarrier` ASC) VISIBLE,
  CONSTRAINT `flights_ibfk_1`
    FOREIGN KEY (`Dest`)
    REFERENCES `usairlineflights2`.`usairports` (`IATA`),
  CONSTRAINT `flights_ibfk_2`
    FOREIGN KEY (`Origin`)
    REFERENCES `usairlineflights2`.`usairports` (`IATA`),
  CONSTRAINT `flights_ibfk_3`
    FOREIGN KEY (`UniqueCarrier`)
    REFERENCES `usairlineflights2`.`carriers` (`CarrierCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
